### ISSUE TITLE
Can the implementation deal with timeevent?

### ISSUE THREAD

**Issue by sdzzlmz** [ModelDriven/fUML-Reference-Implementation#32]
Is there a sample xml related to this implementation, for there is always some issues with xml exported from magicdraw

**Comment by seidewitz** [comment]
The Reference Implementation does not support time events, because they are not included in the standard fUML subset. There is currently work in progress on a submission to the recent OMG [RFP for a Precise Semantics of Time for fUML](https://www.omg.org/cgi-bin/doc.cgi?ad/2017-12-7), which includes a requirement to provide semantics for time events (however, the initial submission deadline for this RFP has been delayed until August of 2020). It has not yet been determined whether the fUML Reference Implementation will be extended to support the new time semantics, once a specification has been completed.

**Comment by seidewitz** [comment]
The Reference Implementation can generally handle XMI files exported from MagicDraw, but it can only execute models within the fUML subset. If you have a general problem with loading XMI from MagicDraw, please submit a separate issue on that and attach a file you are having trouble with.
