### ISSUE TITLE
Working MagicDraw example?

### ISSUE THREAD

**Issue by JDziurlaj** [ModelDriven/fUML-Reference-Implementation#35]
I am testing the interoperability of MagicDraw with the fUML reference implementation. To do this I imported the Hello.uml (generated from the ALF example) and exported it back as MagicDraw XMI. However, when running the resultant XMI in the reference implementation, I get an error `Cannot find Model::Hello`.

Code is [linked here](https://gist.github.com/JDziurlaj/f2590ccccab4695800b62c72cd8c5be5).

Alternatively, is there any working MagicDraw XMI that can be provided as an example?

**Comment by seidewitz** [comment]
The fUML main program does not understand qualified names, so it is looking for an activity with the name "Models::Hello" -- which, of course, isn't found. If you provide just "Hello" for the activity name, then it should work.

However, even then, the activity will not execute properly, because the call behavior action `Call(WriteLine)` in your file has lost its reference to the `WriteLine` behavior. This causes an error, because `behavior` is a mandatory property of a call behavior action.

The reason the reference to `WriteLine` is missing is that the UML files generated by the Alf Reference Implementation are intended to be run within the Eclipse environment. Therefore, they use Eclipse pathmaps for library element references (in this case `pathmap://ALF_LIBRARIES/fUML.library.uml#BasicInputOutput-WriteLine`), which are not understood by MagicDraw. However, even if these are changed to standard URI references, MagicDraw will still not resolve them correctly. And, if you manually set the behavior using the `WriteLine` from the No Magic Cameo SImulation Toolkit implementation of the Foundational Model Library, then the MagicDraw-specific ID for this is used when the model is exported, which is not understood by the Reference Implementation.

I know of no way of resolving this that does not require direct editing of the XML files. Proper handling of standard library model elements, beyond the very basic UML ones, has been a perennial problem for UML tool interoperability.

**Comment by seidewitz** [comment]
You can find some `.mdxml` files used for testing in https://github.com/ModelDriven/fUML-Reference-Implementation/tree/master/org.modeldriven.fuml/src/test/resources/mdxml. These files were originally generated from MagicDraw, but have been modified to run with the Reference Implementation. However, they will not necessarily load back into MagicDraw correctly without special measures.
